In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords')
import re
import numpy as np

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
paragraph = """
Narendra Damodardas Modi[a] (born 17 September 1950) is an Indian politician who has served as the prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindutva paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.

Modi was born and raised in Vadnagar, Bombay State (present-day Gujarat), where he completed his secondary education. He was introduced to the RSS at the age of eight, becoming a full-time worker for the organisation in Gujarat in 1971. The RSS assigned him to the BJP in 1985, and he rose through the party hierarchy, becoming general secretary in 1998.[b] In 2001, Modi was appointed chief minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots[c] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[4] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[d] While his policies as chief minister were credited for encouraging economic growth, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[e]

In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment and reduced spending on healthcare, education, and social-welfare programs. Modi began a high-profile sanitation campaign and weakened or abolished environmental and labour laws. His demonetisation of banknotes in 2016 and introduction of the Goods and Services Tax in 2017 sparked controversy. Modi's administration launched the 2019 Balakot airstrike against an alleged terrorist training camp in Pakistan; the airstrike failed,[5][6] but the action had nationalist appeal.[7] Modi's party won the 2019 general election. In its second term, his administration revoked the special status of Jammu and Kashmir and introduced the Citizenship Amendment Act, prompting widespread protests and spurring the 2020 Delhi riots in which Muslims were brutalised and killed by Hindu mobs.[8][9][10] Three controversial farm laws led to sit-ins by farmers across the country, eventually causing their formal repeal. Modi oversaw India's response to the COVID-19 pandemic, during which, according to the World Health Organization, 4.7 million Indians died.[11][12] In the 2024 general election, Modi's party lost its majority in the lower house of Parliament and formed a government leading the National Democratic Alliance coalition. Following a terrorist attack in Indian-administered Jammu and Kashmir, Modi presided over the 2025 India–Pakistan conflict, which resulted in a ceasefire.
"""

In [ ]:
# Tokenize
sentences = nltk.sent_tokenize(paragraph)

In [ ]:
print(sentences)

['\nNarendra Damodardas Modi[a] (born 17 September 1950) is an Indian politician who has served as the prime minister of India since 2014.', 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi.', 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindutva paramilitary volunteer organisation.', 'He is the longest-serving prime minister outside the Indian National Congress.', 'Modi was born and raised in Vadnagar, Bombay State (present-day Gujarat), where he completed his secondary education.', 'He was introduced to the RSS at the age of eight, becoming a full-time worker for the organisation in Gujarat in 1971.', 'The RSS assigned him to the BJP in 1985, and he rose through the party hierarchy, becoming general secretary in 1998.', '[b] In 2001, Modi was appointed chief minister of Gujarat and elected to the legislative assembly soon after.', 'His administration is conside

In [ ]:
type(sentences)

list

In [ ]:
stemmer = PorterStemmer()

In [ ]:
stemmer.stem('thinking')

'think'

In [ ]:
lemmatizer=WordNetLemmatizer()

In [ ]:
lemmatizer.lemmatize('thinkinig')

'thinkinig'

In [ ]:
corpus=[]

In [ ]:
for i in range(len(sentences)):
  review=re.sub("[^a-zA-Z]"," ",sentences[i])
  review=review.lower()
  #review=review.split()
  corpus.append(review)

In [ ]:
corpus

[' narendra damodardas modi a   born    september       is an indian politician who has served as the prime minister of india since      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindutva paramilitary volunteer organisation ',
 'he is the longest serving prime minister outside the indian national congress ',
 'modi was born and raised in vadnagar  bombay state  present day gujarat   where he completed his secondary education ',
 'he was introduced to the rss at the age of eight  becoming a full time worker for the organisation in gujarat in      ',
 'the rss assigned him to the bjp in       and he rose through the party hierarchy  becoming general secretary in      ',
 ' b  in       modi was appointed chief minister of gujarat and elected to the legislative assembly soon after ',
 'his administration is 

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
#Stemming
for i in sentences:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words('english')):
      print(stemmer.stem(word))

narendra
damodarda
modi
[
]
(
born
17
septemb
1950
)
indian
politician
serv
prime
minist
india
sinc
2014
.
modi
chief
minist
gujarat
2001
2014
member
parliament
(
mp
)
varanasi
.
he
member
bharatiya
janata
parti
(
bjp
)
rashtriya
swayamsevak
sangh
(
rss
)
,
right-w
hindutva
paramilitari
volunt
organis
.
he
longest-serv
prime
minist
outsid
indian
nation
congress
.
modi
born
rais
vadnagar
,
bombay
state
(
present-day
gujarat
)
,
complet
secondari
educ
.
he
introduc
rss
age
eight
,
becom
full-tim
worker
organis
gujarat
1971
.
the
rss
assign
bjp
1985
,
rose
parti
hierarchi
,
becom
gener
secretari
1998
.
[
b
]
in
2001
,
modi
appoint
chief
minist
gujarat
elect
legisl
assembl
soon
.
hi
administr
consid
complicit
2002
gujarat
riot
[
c
]
criticis
manag
crisi
.
accord
offici
record
,
littl
1,000
peopl
kill
,
three-quart
muslim
;
independ
sourc
estim
2,000
death
,
mostli
muslim
.
[
4
]
a
special
investig
team
appoint
suprem
court
india
2012
found
evid
initi
prosecut
proceed
.
[
]
while
polici
chi

In [ ]:
# Lemmatization
for i in sentences:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words('english')):
      print(lemmatizer.lemmatize(word))

Narendra
Damodardas
Modi
[
]
(
born
17
September
1950
)
Indian
politician
served
prime
minister
India
since
2014
.
Modi
chief
minister
Gujarat
2001
2014
member
parliament
(
MP
)
Varanasi
.
He
member
Bharatiya
Janata
Party
(
BJP
)
Rashtriya
Swayamsevak
Sangh
(
RSS
)
,
right-wing
Hindutva
paramilitary
volunteer
organisation
.
He
longest-serving
prime
minister
outside
Indian
National
Congress
.
Modi
born
raised
Vadnagar
,
Bombay
State
(
present-day
Gujarat
)
,
completed
secondary
education
.
He
introduced
RSS
age
eight
,
becoming
full-time
worker
organisation
Gujarat
1971
.
The
RSS
assigned
BJP
1985
,
rose
party
hierarchy
,
becoming
general
secretary
1998
.
[
b
]
In
2001
,
Modi
appointed
chief
minister
Gujarat
elected
legislative
assembly
soon
.
His
administration
considered
complicit
2002
Gujarat
riot
[
c
]
criticised
management
crisis
.
According
official
record
,
little
1,000
people
killed
,
three-quarters
Muslim
;
independent
source
estimated
2,000
death
,
mostly
Muslim
.
[
4
]
A
Spec

**Bag of Word(BOW)**

In [ ]:
# Bag of Word(BOW)
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
x=cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_

{'narendra': 145,
 'damodardas': 55,
 'modi': 140,
 'born': 31,
 'september': 195,
 'is': 118,
 'an': 14,
 'indian': 109,
 'politician': 166,
 'who': 234,
 'has': 93,
 'served': 196,
 'as': 18,
 'the': 217,
 'prime': 170,
 'minister': 138,
 'of': 149,
 'india': 108,
 'since': 200,
 'was': 227,
 'chief': 39,
 'gujarat': 91,
 'from': 85,
 'to': 222,
 'and': 15,
 'member': 136,
 'parliament': 161,
 'mp': 142,
 'for': 80,
 'varanasi': 225,
 'he': 94,
 'bharatiya': 28,
 'janata': 121,
 'party': 163,
 'bjp': 29,
 'rashtriya': 179,
 'swayamsevak': 212,
 'sangh': 190,
 'rss': 189,
 'right': 186,
 'wing': 237,
 'hindutva': 101,
 'paramilitary': 160,
 'volunteer': 226,
 'organisation': 153,
 'longest': 131,
 'serving': 198,
 'outside': 155,
 'national': 146,
 'congress': 45,
 'raised': 178,
 'in': 105,
 'vadnagar': 224,
 'bombay': 30,
 'state': 209,
 'present': 168,
 'day': 56,
 'where': 231,
 'completed': 42,
 'his': 102,
 'secondary': 193,
 'education': 65,
 'introduced': 114,
 'at': 21,
 'age

In [ ]:
len(cv.vocabulary_)

241

In [ ]:
corpus[1]

'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi '

In [ ]:
x[1].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
x[0].toarray().shape

(1, 241)

In [ ]:
corpus=[]

In [ ]:
cv = CountVectorizer(binary=True)

In [ ]:
corpus = []

In [ ]:
stop_words_set = set(stopwords.words('english')) # Ensure stopwords are loaded

In [ ]:
for i in range(len(sentences)):
  review = re.sub("[^a-zA-Z]"," ",sentences[i])
  review = review.lower()
  words = review.split()
  # Remove stopwords and join words back into a string
  filtered_words = [word for word in words if word not in stop_words_set]
  processed_sentence = " ".join(filtered_words)
  corpus.append(processed_sentence)

In [ ]:
x=cv.fit_transform(corpus)

In [ ]:
x[1].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0]])

In [ ]:
stop_words_set = set(stopwords.words('english')) # Create a set of stopwords for efficient lookup

In [ ]:
for i in range(len(sentences)):
  review = re.sub("[^a-zA-Z]"," ",sentences[i])
  review = review.lower()
  words = review.split()
  # Remove stopwords and join words back into a string
  filtered_words = [word for word in words if word not in stop_words_set]
  processed_sentence = " ".join(filtered_words)
  corpus.append(processed_sentence)

In [ ]:
# Convert to Binary
cv = CountVectorizer(binary=True)

In [ ]:
#cv = CountVectorizer(binary=True, ngram_range=(2,3))

In [ ]:
cv

CountVectorizer(binary=True)

In [ ]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

 **TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
cv = TfidfVectorizer()

In [ ]:
x=cv.fit_transform(corpus)

In [ ]:
corpus[0]

'narendra damodardas modi born september indian politician served prime minister india since'

In [ ]:
x[0]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12 stored elements and shape (1, 204)>

In [ ]:
x[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28996663,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3356734 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [ ]:
#cv=TfidfVectorizer(ngram_range=(2,3))

In [ ]:
x[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28996663,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3356734 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [ ]:
#cv=TfidfVectorizer(ngram_range=(2,3),max_features=3)

In [ ]:
x[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28996663,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3356734 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

**Word Embeddings (CBOW Model from Scratch using ANN)**

In [ ]:
corpus = ["""
Narendra Damodardas Modi (born 17 September 1950) is an Indian politician who has served as the prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindutva paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress.

Modi was born and raised in Vadnagar, Bombay State (present-day Gujarat), where he completed his secondary education. He was introduced to the RSS at the age of eight, becoming a full-time worker for the organisation in Gujarat in 1971. The RSS assigned him to the BJP in 1985, and he rose through the party hierarchy, becoming general secretary in 1998.[b] In 2001, Modi was appointed chief minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots[c] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[4] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[d] While his policies as chief minister were credited for encouraging economic growth, his administration was criticised for failing to significantly improve health, poverty and education indices in the state.[e]

In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment and reduced spending on healthcare, education, and social-welfare programs. Modi began a high-profile sanitation campaign and weakened or abolished environmental and labour laws. His demonetisation of banknotes in 2016 and introduction of the Goods and Services Tax in 2017 sparked controversy. Modi's administration launched the 2019 Balakot airstrike against an alleged terrorist training camp in Pakistan; the airstrike failed,[5][6] but the action had nationalist appeal.[7] Modi's party won the 2019 general election. In its second term, his administration revoked the special status of Jammu and Kashmir and introduced the Citizenship Amendment Act, prompting widespread protests and spurring the 2020 Delhi riots in which Muslims were brutalised and killed by Hindu mobs.[8][9][10] Three controversial farm laws led to sit-ins by farmers across the country, eventually causing their formal repeal. Modi oversaw India's response to the COVID-19 pandemic, during which, according to the World Health Organization, 4.7 million Indians died.[11][12] In the 2024 general election, Modi's party lost its majority in the lower house of Parliament and formed a government leading the National Democratic Alliance coalition. Following a terrorist attack in Indian-administered Jammu and Kashmir, Modi presided over the 2025 India–Pakistan conflict, which resulted in a ceasefire.
"""]

In [ ]:
def preprocess_text(text):

    text = text.lower()

    text = re.sub(r'[^a-z\s]', '', text)

    tokens = word_tokenize(text)

    tokens = [w for w in tokens if w not in stopwords.words('english')]

    return tokens

In [ ]:
tokenized_corpus = [preprocess_text(sentence) for sentence in corpus]
print("\n--- Tokenized Corpus using NLTK ---")
for sent in tokenized_corpus:
    print(sent)


--- Tokenized Corpus using NLTK ---
['narendra', 'damodardas', 'modi', 'born', 'september', 'indian', 'politician', 'served', 'prime', 'minister', 'india', 'since', 'modi', 'chief', 'minister', 'gujarat', 'member', 'parliament', 'mp', 'varanasi', 'member', 'bharatiya', 'janata', 'party', 'bjp', 'rashtriya', 'swayamsevak', 'sangh', 'rss', 'rightwing', 'hindutva', 'paramilitary', 'volunteer', 'organisation', 'longestserving', 'prime', 'minister', 'outside', 'indian', 'national', 'congress', 'modi', 'born', 'raised', 'vadnagar', 'bombay', 'state', 'presentday', 'gujarat', 'completed', 'secondary', 'education', 'introduced', 'rss', 'age', 'eight', 'becoming', 'fulltime', 'worker', 'organisation', 'gujarat', 'rss', 'assigned', 'bjp', 'rose', 'party', 'hierarchy', 'becoming', 'general', 'secretary', 'b', 'modi', 'appointed', 'chief', 'minister', 'gujarat', 'elected', 'legislative', 'assembly', 'soon', 'administration', 'considered', 'complicit', 'gujarat', 'riotsc', 'criticised', 'managemen

In [ ]:
# Build vocabulary from tokenized corpus
vocab = set([word for sent in tokenized_corpus for word in sent])
word2id = {word: i for i, word in enumerate(vocab)}
id2word = {i: word for word, i in word2id.items()}
vocab_size = len(vocab)

print("\nVocabulary Size:", vocab_size)
print("Word to Index Mapping:", word2id)



Vocabulary Size: 204
Word to Index Mapping: {'becoming': 0, 'bharatiya': 1, 'repeal': 2, 'congress': 3, 'covid': 4, 'brutalised': 5, 'goods': 6, 'appointed': 7, 'across': 8, 'indianadministered': 9, 'terrorist': 10, 'sangh': 11, 'prime': 12, 'little': 13, 'people': 14, 'poverty': 15, 'labour': 16, 'increased': 17, 'environmental': 18, 'status': 19, 'prompting': 20, 'policies': 21, 'muslim': 22, 'supreme': 23, 'sanitation': 24, 'introduced': 25, 'demonetisation': 26, 'failing': 27, 'organization': 28, 'pakistan': 29, 'independent': 30, 'citizenship': 31, 'direct': 32, 'september': 33, 'general': 34, 'riots': 35, 'mp': 36, 'initiate': 37, 'muslims': 38, 'pandemic': 39, 'programs': 40, 'national': 41, 'since': 42, 'causing': 43, 'act': 44, 'damodardas': 45, 'country': 46, 'widespread': 47, 'official': 48, 'presentday': 49, 'hindu': 50, 'revoked': 51, 'alliance': 52, 'paramilitary': 53, 'modis': 54, 'served': 55, 'vadnagar': 56, 'government': 57, 'abolished': 58, 'riotsc': 59, 'economic':

In [ ]:
#Generate CBOW Training Pairs

In [ ]:
window_size = 4

In [ ]:
data = []

In [ ]:
for sentence in tokenized_corpus:
    for idx, word in enumerate(sentence):
        target = word
        context = []
        for i in range(idx - window_size, idx + window_size + 1):
            if i != idx and i >= 0 and i < len(sentence):
                context.append(sentence[i])
        if len(context) > 0:
            data.append((context, target))

In [ ]:
print("\n--- Sample CBOW (Context, Target) Pairs ---")
for i in range(5):
    print(data[i])


--- Sample CBOW (Context, Target) Pairs ---
(['damodardas', 'modi', 'born', 'september'], 'narendra')
(['narendra', 'modi', 'born', 'september', 'indian'], 'damodardas')
(['narendra', 'damodardas', 'born', 'september', 'indian', 'politician'], 'modi')
(['narendra', 'damodardas', 'modi', 'september', 'indian', 'politician', 'served'], 'born')
(['narendra', 'damodardas', 'modi', 'born', 'indian', 'politician', 'served', 'prime'], 'september')


In [ ]:
#Prepare Training Data

In [ ]:
def prepare_training_data(data, word2id):
    X = []
    y = []
    for context, target in data:
        context_ids = [word2id[w] for w in context if w in word2id]
        if not context_ids:
            continue
        target_id = word2id[target]
        X.append(np.mean(context_ids))
        y.append(target_id)
    return np.array(X), np.array(y)

In [ ]:
X, y = prepare_training_data(data, word2id)

In [ ]:
# One-hot encode targets
y_onehot = np.zeros((len(y), vocab_size))
for i, word_id in enumerate(y):
    y_onehot[i, word_id] = 1

In [ ]:
#Build Artificial Neural Network (CBOW Model)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Lambda, Dense, Input
from tensorflow.keras import backend as K

In [ ]:
embedding_dim = 10  # Embedding vector size

In [ ]:
cbow_model = Sequential()
cbow_model.add(Input(shape=(1,)))   # Explicit input shape
cbow_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim))
cbow_model.add(Lambda(lambda x: K.mean(x, axis=1)))
cbow_model.add(Dense(vocab_size, activation='softmax'))

In [ ]:
cbow_model.compile(loss='categorical_crossentropy', optimizer='adam')

In [ ]:
print("\n--- CBOW Model Summary ---")
cbow_model.summary()


--- CBOW Model Summary ---


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 1, 10)          │         2,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 204)            │         2,244 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,284 (16.73 KB)

 Trainable params: 4,284 (16.73 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Train the Model

In [ ]:
X_reshaped = X.reshape(-1, 1)
cbow_model.fit(X_reshaped, y_onehot, epochs=100, verbose=0)
print("\nCBOW Model Trained Successfully!")


CBOW Model Trained Successfully!


In [ ]:
# Extract embedding weights
weights = cbow_model.get_weights()[0]

In [ ]:
print("\n--- Word Embeddings (Learned from CBOW Model) ---")
for word, idx in word2id.items():
    print(f"{word}: {weights[idx]}")


--- Word Embeddings (Learned from CBOW Model) ---
becoming: [-0.03146528  0.03181771  0.0405185   0.00424502 -0.01105902  0.02595726
 -0.0289624   0.03126338 -0.00190047  0.04663995]
bharatiya: [ 0.01222456  0.00284805 -0.00596943 -0.03332939  0.04405818  0.01021031
  0.03138204  0.04762622  0.02243387  0.0483898 ]
repeal: [ 0.00841892  0.03979242 -0.01837562  0.02199731  0.0190843   0.04217236
 -0.00795015  0.03664513  0.04341394 -0.04237739]
congress: [-0.03390106 -0.02886351 -0.00140569 -0.04848267 -0.01264983  0.02750281
  0.00816151  0.01272199 -0.0359927   0.03888253]
covid: [-0.02627686  0.02144786  0.00737662  0.0023931  -0.03728657 -0.04479304
  0.03513117 -0.03055998 -0.00339033  0.02425928]
brutalised: [ 0.03234104  0.0265565  -0.01447071 -0.02951007 -0.04677866 -0.02127283
 -0.0119343  -0.00211004 -0.04151692  0.00123104]
goods: [-0.02495934  0.03849466 -0.01933742 -0.01517004 -0.04483603  0.04159585
  0.02167156 -0.0339811  -0.01549704 -0.04044852]
appointed: [ 0.00908314